import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sample Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav>
          <ul>
            <li>
              <Link href="/tasks" passHref>
                <a>Tasks</a>
              </Link>
            </li>
            <li>
              <Link href="/tasks/create" passHref>
                <a>Make New Task</a>
              </Link>
            </li>
          </ul>
        </nav>
        <header>
          <h2>Simple Task App</h2>
        </header>
      </main>
    </div>
  );
};

export default Home;
